export const TICKET_REQUEST = 'TICKET_REQUEST'
export const TICKET_SUCCESS = 'TICKET_SUCCESS'
export const TICKET_FAIL = 'TICKET_FAIL'

export const TICKET_CREATE_SUCCESS = 'TICKET_CREATE_SUCCESS'
export const TICKET_CREATE_FAIL = 'TICKET_CREATE_FAIL'

export const IS_URGENT_TRUE = 'IS_URGENT_TRUE'
export const IS_URGENT_FALSE = 'IS_URGENT_FALSE'

export const IS_RESOLVED_TRUE = 'IS_RESOLVED_TRUE'
export const IS_RESOLVED_FALSE = 'IS_RESOLVED_FALSE'

export const GET_ALL_TICKETS_TYPE_REQUEST = 'GET_ALL_TICKETS_TYPE_REQUEST'
export const GET_ALL_TICKETS_TYPE_SUCCESS = 'GET_ALL_TICKETS_TYPE_SUCCESS'
export const GET_ALL_TICKETS_TYPE_FAIL = 'GET_ALL_TICKETS_TYPE_FAIL'

export const DELETE_TICKET = 'DELETE_TICKET'

export const UPDATE_RESOLVED = 'UPDATE_RESOLVED'

export const FILTER_BY_DEPARMENT = 'FILTER_BY_DEPARMENT'

export const CLEAR_ALL_STATE = 'CLEAR_ALL_STATE'
